name: ecommerce
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animate_do: ^2.1.0
  cached_network_image: ^3.1.0
  cloud_firestore: ^3.1.8
  csc_picker: ^0.2.6
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  firebase_auth: ^3.3.7
  firebase_core: ^1.12.0
  firebase_storage: ^10.2.8
  flutter:
    sdk: flutter
  flutter_offline: ^2.1.0
  flutter_svg: ^1.0.3
  geocoding: null
  get_it: ^7.2.0
  google_fonts: 2.3.1
  google_maps_flutter: ^2.1.10
  google_sign_in: ^5.4.0
  image_picker: ^0.8.5+3
  images_picker: ^1.2.11
  intl_phone_number_input: ^0.7.0+2
  location: ^4.2.0
  lottie: ^1.3.0
  map_launcher: ^2.2.3
  overlay_support: ^2.0.1
  photo_view: ^0.14.0
  pinput: ^2.2.11
  search_page: ^2.0.0+1
  provider: ^6.0.1
  intl:
  shimmer: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  timeago_flutter: ^1.1.0
  timer_builder: ^2.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/jsons/
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
